### ISSUE TITLE
Styling when using validationState

### ISSUE THREAD

**Issue by murphyke** [affinipay/react-bootstrap-autosuggest#15]
When, e.g. `validationState` is 'error', the textbox portion of the combo-box is mostly bordered in red, as expected. However, the right side of the textbox is not bordered in red, because it is overlaid by the dropdown disclosure button on the right side, which doesn't get any special styling.

![screen shot 2018-05-29 at 2 24 58 pm](https://user-images.githubusercontent.com/928642/40677764-9da161b6-634c-11e8-9c8d-0bd4b4e397f8.png)

**Comment by trevorr** [comment]
It appears to work correctly on the demo page: https://affinipay.github.io/react-bootstrap-autosuggest/#react-bootstrap

Perhaps you're not pulling in the [stylesheet](https://github.com/affinipay/react-bootstrap-autosuggest/blob/master/src/Autosuggest.scss)? It used to be included automatically (see #1), but that seemed to cause more harm than good, so it's now (as of 0.5) left to the application to include. The demo uses Webpack's Sass Loader to [`import` it](https://github.com/affinipay/react-bootstrap-autosuggest/blob/master/demo/demo.js#L19).

**Comment by murphyke** [comment]
OK, I will think about wading into scary webpack land, although I have already styled it enough for my purposes.

I do think it would be good to briefly document the styling situation on the "basic usage" and full documentation pages. Apologies if it's there and I missed it.

**Comment by trevorr** [comment]
The documentation note about it is in the [README](https://github.com/affinipay/react-bootstrap-autosuggest/blob/master/README.md):

> Note that the CSS styles required by the component are no longer included automatically as of version 0.5. For Webpack users, the recommended approach is to configure sass-loader and then `require('Autosuggest.scss')` in your application. You can either specify the full path (e.g. `./node_modules/react-bootstrap-autosuggest/src/Autosuggest.scss`) or include `./node_modules/react-bootstrap-autosuggest/src` as a search path.

If you have any helpful elaboration to offer, I'll gladly take a pull request.
