### ISSUE TITLE
Don't show dropdown menu if there are no matches

### ISSUE THREAD

**Issue by murphyke** [affinipay/react-bootstrap-autosuggest#17]
The dropdown menu looks awkward when it is empty, as when the user types an entry that initially triggers the menu but then becomes non-matching:

![screen shot 2018-06-08 at 1 47 37 pm](https://user-images.githubusercontent.com/928642/41173748-07c0f134-6b26-11e8-8054-1dd5c43d306f.png)

For comparison, the dropdown menu is *not* displayed when you start typing in the input box and there are no matches, e.g. you type `z` and there are no `z`s in any of the menu items.

I think it would look better to have the menu disappear if the user's typing results in no matching items. What are your thoughts?

**Comment by trevorr** [comment]
Are you doing something to disable the "Show all" item that usually exists at the bottom of the suggestions? Is it a dynamic data set, for instance?

**Comment by murphyke** [comment]
No, it's not a dynamic data set. So far I haven't even tested with more than a small handful of entries.

This is how I'm using it at the moment:

```
<Autosuggest
  datalist={cohorts}
  value={this.state.cohortName}
  placeholder="Existing or new cohort name"
  onChange={this.handleCohortNameChange}
  onBlur={this.handleCohortNameBlur}
/>
```

**Comment by trevorr** [comment]
Any idea why "Show all" is not appearing, as it does on the [demo page](https://affinipay.github.io/react-bootstrap-autosuggest/)? I've never seen this empty box behavior. Maybe one of your event handlers is emptying `cohorts`? This may well be a bug/oversight in the component; I just want to make sure we completely understand it before making changes.

**Comment by murphyke** [comment]
Hold on. I am still not using the official styles ....

**Comment by murphyke** [comment]
I tried to apply your webpack recipe from #1, but I'm getting errors that may be due to a peer dependency morass. I will have to get back to this maybe next week.

**Comment by trevorr** [comment]
Did you ever figure out what's going on or get the official styles working?

**Comment by murphyke** [comment]
Thanks for the reminder; I will make a reminder to check on that next week.

**Comment by murphyke** [comment]
> Did you ever figure out what's going on or get the official styles working?

I won't be able to get to this for ... a few months.  Thanks for bearing with me thus far.

I'm going to close this. I assume I will figure out the webpack config when I have to.
