### ISSUE TITLE
Force the autosuggest to pick the element on top of the list from another component

### ISSUE THREAD

**Issue by Gothbag** [affinipay/react-bootstrap-autosuggest#6]
Greetings,
I'm looking for a way to be able to force the Autosuggest to select the first suggestion from another component, like say a Search button, given what's been typed in. Is that possible?

Thank you very much

**Comment by trevorr** [comment]
Could you be a little more specific about the scenario? It should be easy to change the selected item in general, since you just need to set the React state, but I'm guessing that's not what you're after. A before and after picture of the interaction, even if just a rough sketch, would be helpful.

**Comment by Gothbag** [comment]
Thanks for the attention. Sorry, my question was not well phrased nor thought out. I'm closing this.
