### ISSUE TITLE
Cannot resolve module 'Autosuggest.scss'

### ISSUE THREAD

**Issue by rrivem** [affinipay/react-bootstrap-autosuggest#9]
I'm trying to import the react-bootstrap-autosuggest library into my project. I followed the instructions and installed react-bootstrap and react-bootstrap-autosuggest as dependencies, and configured the webpack loader sass-loader as dev dependency.

But the Autosuggest.js is trying to import 'Autosuggest.scss' and so it cannot find the file, which by the way is not present in the lib folder, and so reports the error "Cannot resolve module 'Autosuggest.scss'".

I've tried copying the scss file from the src folder to the lib folder and modifying the [Autosuggest.js line 11 (line 38 in lib/Autosuggest.js file)](https://github.com/affinipay/react-bootstrap-autosuggest/blob/master/src/Autosuggest.js#L11) with `require('./Autosuggest.scss')`, but then it fails once again searching for bootstrap scss files.

Am I missing some configuration?

Thanks,
Rodrigo

**Comment by trevorr** [comment]
Don't forget to check closed issues when searching GitHub: https://github.com/affinipay/react-bootstrap-autosuggest/issues/1
